# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIjC9RExYu9VWbk7ge6A7vY6m14P3LpK
"""

import os
from flask import Flask, request, abort

from linebot.v3 import WebhookHandler
from linebot.v3.exceptions import InvalidSignatureError
from linebot.v3.webhooks import MessageEvent, TextMessageContent
from linebot.v3.messaging import (
    Configuration, ApiClient, MessagingApi,
    ReplyMessageRequest,
    TextMessage,TemplateMessage, ConfirmTemplate, MessageAction,
    ButtonsTemplate,
    URIAction,
    CarouselTemplate,
    CarouselColumn,
    LocationAction,
    URIAction,
    PostbackAction,CameraAction,CameraRollAction
)

app = Flask(__name__)

configuration = Configuration(access_token=os.getenv('LINE_CHANNEL_ACCESS_TOKEN'))
line_handler = WebhookHandler(os.getenv('LINE_CHANNEL_SECRET'))

@app.route("/", methods=['GET'])
def index():
  return 'hello!'

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        line_handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'

@line_handler.add(MessageEvent, message=TextMessageContent)
def handle_message(event):
    with ApiClient(configuration) as api_client:
        line_bot_api = MessagingApi(api_client)

        action = event.message.text
        if action =='confirm':
          template=ConfirmTemplate(
            text="你是傻子嗎？",
            actions=[
              MessageAction(label="是", text="我很有自知之明的"),
              MessageAction(label="否", text="我是傻子")
        ]
    )
          reply = TemplateMessage(
              alt_text="這是確認視窗",
              template=template
    )
        elif  action == 'carousel':
          carousel_template = CarouselTemplate(
              columns=[
          CarouselColumn(
            thumbnail_image_url='https://img.carstuff.com.tw/images/stories/2021/Jason/05/13/VW/2022-mercedes-maybach-s6803.jpeg',
            title='Mercedes maybach s680',
            text='價格 $300。',
            actions=[
                URIAction(label='查看詳情', uri='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
                MessageAction(label='加入購物車', text='我是傻子')
            ]
        ),
          CarouselColumn(
            thumbnail_image_url='https://vancouverboulevard.com/wp-content/uploads/2022/04/1_Phantom-Orchid-Front-3_4.png',
            title='Rolls-Royce Phantom Orchid',
            text='價格 $200。',
            actions=[
                URIAction(label='查看詳情', uri='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
                MessageAction(label='加入購物車', text='我是大傻子')
            ]
        )
        ]
          )
          reply = TemplateMessage(
              alt_text="這是輪播視窗",
              template=carousel_template
          )
        else:
          reply = TextMessage(text='Thanks!')




        line_bot_api.reply_message(
            ReplyMessageRequest(
                reply_token=event.reply_token,
                messages=[
                    reply
                ]
            )
        )
